# Generated by Django 5.1.3 on 2024-11-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nights',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
