# Generated by Django 5.1.3 on 2024-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
